# Generated by Django 4.1.4 on 2023-01-01 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0003_coupon_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='use_from',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='use_to',
        ),
    ]
