# Generated by Django 4.1.4 on 2023-01-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0004_remove_coupon_use_from_remove_coupon_use_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='use_from',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='use_to',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='active',
            field=models.BooleanField(),
        ),
    ]
